// Fixed UI copy; no translation service runs during development or builds.
// code | native name | notice | open TXT | all languages | translation date label
const rows = `
af|Afrikaans|Hierdie taaladres bied 'n masjienvertaling van die artikels, slegs as teks. Die vertaling is nie onafhanklik nagegaan nie en kan verouderd wees. Die volledige webwerf is net in Tsjeggies en Engels beskikbaar.|Lees die vertaling (.txt)|Alle tale|Datum van die teksvertaling
ak|Akan|Saa kasa yi wɛb adrɛs no de afiri nkyerɛase a ɛyɛ nsɛm nko ara ma. Wɔnnhwɛɛ nkyerɛase no mu wɔ ɔkwan foforo so, na ebia ɛnyɛ foforo. Wɛbsaet no nyinaa wɔ Czech ne Borɔfo nkutoo mu.|Kenkan nkyerɛase no (.txt)|Kasa nyinaa|Nsɛm no nkyerɛase da
am|አማርኛ|ይህ የቋንቋ አድራሻ የጽሑፎቹን የማሽን ትርጉም በጽሑፍ ብቻ ያቀርባል። ትርጉሙ በገለልተኛ አካል አልተገመገመም፣ ወቅታዊም ላይሆን ይችላል። ሙሉ ድረ ገጹ በቼክኛ እና በእንግሊዝኛ ብቻ ይገኛል።|ትርጉሙን ያንብቡ (.txt)|ሁሉም ቋንቋዎች|የጽሑፍ ትርጉም ቀን
ar|العربية|يعرض هذا العنوان اللغوي ترجمة آلية للمقالات بصيغة نصية فقط. لم تخضع الترجمة لمراجعة مستقلة وقد لا تكون محدثة. الموقع الكامل متاح بالتشيكية والإنجليزية فقط.|قراءة الترجمة (.txt)|جميع اللغات|تاريخ الترجمة النصية
as|অসমীয়া|এই ভাষাৰ ঠিকনাত প্ৰবন্ধবোৰৰ কেৱল পাঠ্য ৰূপত যান্ত্ৰিক অনুবাদ দিয়া হৈছে। অনুবাদটো স্বতন্ত্ৰভাৱে পৰীক্ষা কৰা হোৱা নাই আৰু পুৰণি হ’ব পাৰে। সম্পূৰ্ণ ৱেবছাইট কেৱল চেক আৰু ইংৰাজী ভাষাত উপলব্ধ।|অনুবাদ পঢ়ক (.txt)|সকলো ভাষা|পাঠ্য অনুবাদৰ তাৰিখ
az|Azərbaycanca|Bu dil ünvanı məqalələrin yalnız mətn şəklində maşın tərcüməsini təqdim edir. Tərcümə müstəqil şəkildə yoxlanılmayıb və köhnəlmiş ola bilər. Tam sayt yalnız çex və ingilis dillərində mövcuddur.|Tərcüməni oxuyun (.txt)|Bütün dillər|Mətn tərcüməsinin tarixi
be|Беларуская|Гэты моўны адрас прапануе машынны пераклад артыкулаў толькі ў тэкставым выглядзе. Пераклад не прайшоў незалежную праверку і можа быць састарэлым. Поўны сайт даступны толькі на чэшскай і англійскай мовах.|Чытаць пераклад (.txt)|Усе мовы|Дата тэкставага перакладу
bg|Български|Този езиков адрес предлага машинен превод на статиите само като текст. Преводът не е проверен независимо и може да е остарял. Пълният сайт е достъпен само на чешки и английски.|Прочетете превода (.txt)|Всички езици|Дата на текстовия превод
bn|বাংলা|এই ভাষার ঠিকানায় নিবন্ধগুলির যান্ত্রিক অনুবাদ শুধু পাঠ্য হিসেবে দেওয়া হয়েছে। অনুবাদটি স্বাধীনভাবে যাচাই করা হয়নি এবং পুরোনো হতে পারে। সম্পূর্ণ ওয়েবসাইট শুধু চেক ও ইংরেজিতে উপলব্ধ।|অনুবাদ পড়ুন (.txt)|সব ভাষা|পাঠ্য অনুবাদের তারিখ
bs|Bosanski|Ova jezička adresa nudi mašinski prijevod članaka samo u tekstualnom obliku. Prijevod nije nezavisno provjeren i može biti zastario. Potpuna web-stranica dostupna je samo na češkom i engleskom.|Pročitajte prijevod (.txt)|Svi jezici|Datum tekstualnog prijevoda
ca|Català|Aquesta adreça lingüística ofereix una traducció automàtica dels articles només en text. La traducció no s'ha revisat de manera independent i pot estar desactualitzada. El web complet només està disponible en txec i anglès.|Llegiu la traducció (.txt)|Totes les llengües|Data de la traducció de text
ceb|Cebuano|Kini nga adres sa pinulongan nagtanyag og awtomatikong hubad sa mga artikulo isip teksto lamang. Ang hubad wala masusi sa usa ka independente nga tawo ug mahimong karaan na. Ang kompleto nga website anaa lamang sa Czech ug English.|Basaha ang hubad (.txt)|Tanang pinulongan|Petsa sa hubad sa teksto
cy|Cymraeg|Mae'r cyfeiriad iaith hwn yn cynnig cyfieithiad peirianyddol o'r erthyglau fel testun yn unig. Nid yw'r cyfieithiad wedi'i adolygu'n annibynnol a gall fod yn hen. Dim ond yn Tsieceg a Saesneg y mae'r wefan lawn ar gael.|Darllen y cyfieithiad (.txt)|Pob iaith|Dyddiad y cyfieithiad testun
da|Dansk|Denne sprogadresse tilbyder en maskinoversættelse af artiklerne som ren tekst. Oversættelsen er ikke gennemgået uafhængigt og kan være forældet. Det fulde websted findes kun på tjekkisk og engelsk.|Læs oversættelsen (.txt)|Alle sprog|Dato for tekstoversættelsen
de|Deutsch|Diese Sprachadresse bietet eine maschinelle Übersetzung der Artikel als reinen Text. Die Übersetzung wurde nicht unabhängig geprüft und kann veraltet sein. Die vollständige Website ist nur auf Tschechisch und Englisch verfügbar.|Übersetzung lesen (.txt)|Alle Sprachen|Datum der Textübersetzung
el|Ελληνικά|Αυτή η γλωσσική διεύθυνση προσφέρει αυτόματη μετάφραση των άρθρων μόνο ως κείμενο. Η μετάφραση δεν έχει ελεγχθεί ανεξάρτητα και μπορεί να είναι παρωχημένη. Ο πλήρης ιστότοπος διατίθεται μόνο στα τσεχικά και στα αγγλικά.|Διαβάστε τη μετάφραση (.txt)|Όλες οι γλώσσες|Ημερομηνία μετάφρασης κειμένου
es|Español|Esta dirección de idioma ofrece una traducción automática de los artículos solo en texto. La traducción no se ha revisado de forma independiente y puede estar desactualizada. El sitio completo solo está disponible en checo e inglés.|Leer la traducción (.txt)|Todos los idiomas|Fecha de la traducción de texto
et|Eesti|See keeleaadress pakub artiklite masintõlget ainult tekstina. Tõlget pole sõltumatult kontrollitud ja see võib olla aegunud. Täielik veebisait on saadaval ainult tšehhi ja inglise keeles.|Loe tõlget (.txt)|Kõik keeled|Tekstitõlke kuupäev
eu|Euskara|Hizkuntza-helbide honek artikuluen itzulpen automatikoa eskaintzen du, testu hutsean. Itzulpena ez da modu independentean berrikusi eta zaharkituta egon daiteke. Webgune osoa txekieraz eta ingelesez bakarrik dago eskuragarri.|Irakurri itzulpena (.txt)|Hizkuntza guztiak|Testu-itzulpenaren data
fa|فارسی|این نشانی زبانی، ترجمهٔ ماشینی مقاله‌ها را فقط به صورت متن ارائه می‌کند. ترجمه به‌طور مستقل بررسی نشده و ممکن است به‌روز نباشد. وب‌سایت کامل فقط به زبان‌های چکی و انگلیسی در دسترس است.|خواندن ترجمه (.txt)|همهٔ زبان‌ها|تاریخ ترجمهٔ متنی
fi|Suomi|Tämä kieliosoite tarjoaa artikkeleiden konekäännöksen pelkkänä tekstinä. Käännöstä ei ole tarkistettu riippumattomasti, ja se voi olla vanhentunut. Täysi verkkosivusto on saatavilla vain tšekiksi ja englanniksi.|Lue käännös (.txt)|Kaikki kielet|Tekstikäännöksen päiväys
fil|Filipino|Nagbibigay ang adres na ito para sa wika ng awtomatikong salin ng mga artikulo bilang teksto lamang. Hindi ito nasuri nang hiwalay at maaaring hindi napapanahon. Ang buong website ay nasa Czech at Ingles lamang.|Basahin ang salin (.txt)|Lahat ng wika|Petsa ng salin ng teksto
fo|Føroyskt|Henda máladressan bjóðar eina maskinumseting av greinunum sum reinan tekst. Umsetingin er ikki óheft eftirkannað og kann vera ótíðarhóskandi. Øll heimasíðan er bert tøk á kekkiskum og enskum.|Les umsetingina (.txt)|Øll mál|Dagfesting hjá tekstumsetingini
fr|Français|Cette adresse linguistique propose une traduction automatique des articles en texte seul. La traduction n'a pas fait l'objet d'une vérification indépendante et peut être obsolète. Le site complet est disponible uniquement en tchèque et en anglais.|Lire la traduction (.txt)|Toutes les langues|Date de la traduction du texte
fy|Frysk|Dit taaladres biedt in masine-oersetting fan de artikels as allinnich tekst. De oersetting is net ûnôfhinklik neisjoen en kin ferâldere wêze. De folsleine webside is allinnich yn it Tsjechysk en Ingelsk beskikber.|Lês de oersetting (.txt)|Alle talen|Datum fan de tekstoersetting
ga|Gaeilge|Cuireann an seoladh teanga seo aistriúchán meaisín ar na hailt ar fáil mar théacs amháin. Ní dhearnadh athbhreithniú neamhspleách ar an aistriúchán agus d'fhéadfadh sé a bheith as dáta. Níl an suíomh iomlán ar fáil ach i Seicis agus i mBéarla.|Léigh an t-aistriúchán (.txt)|Gach teanga|Dáta an aistriúcháin téacs
gl|Galego|Este enderezo de idioma ofrece unha tradución automática dos artigos só en texto. A tradución non foi revisada de forma independente e pode estar desactualizada. O sitio completo só está dispoñible en checo e inglés.|Ler a tradución (.txt)|Todos os idiomas|Data da tradución de texto
gu|ગુજરાતી|આ ભાષાના સરનામે લેખોનો મશીન અનુવાદ માત્ર લખાણ તરીકે આપવામાં આવે છે. અનુવાદની સ્વતંત્ર સમીક્ષા થઈ નથી અને તે જૂનો હોઈ શકે છે. સંપૂર્ણ વેબસાઇટ માત્ર ચેક અને અંગ્રેજીમાં ઉપલબ્ધ છે.|અનુવાદ વાંચો (.txt)|બધી ભાષાઓ|લખાણના અનુવાદની તારીખ
ha|Hausa|Wannan adireshin harshe yana ba da fassarar na'ura ta makaloli a rubutu kawai. Ba a yi bitar fassarar da kanta ba kuma tana iya zama tsohuwa. Cikakken shafin yana samuwa ne kawai cikin Czech da Turanci.|Karanta fassarar (.txt)|Dukkan harsuna|Ranar fassarar rubutun
he|עברית|כתובת השפה הזו מציעה תרגום מכונה של המאמרים כטקסט בלבד. התרגום לא עבר בדיקה עצמאית ועלול להיות לא מעודכן. האתר המלא זמין רק בצ'כית ובאנגלית.|קריאת התרגום (.txt)|כל השפות|תאריך תרגום הטקסט
hi|हिन्दी|इस भाषा के पते पर लेखों का मशीनी अनुवाद केवल पाठ के रूप में उपलब्ध है। अनुवाद की स्वतंत्र समीक्षा नहीं हुई है और यह पुराना हो सकता है। पूरी वेबसाइट केवल चेक और अंग्रेज़ी में उपलब्ध है।|अनुवाद पढ़ें (.txt)|सभी भाषाएँ|पाठ के अनुवाद की तिथि
hr|Hrvatski|Ova jezična adresa nudi strojni prijevod članaka samo u tekstualnom obliku. Prijevod nije neovisno provjeren i može biti zastario. Potpuna mrežna stranica dostupna je samo na češkom i engleskom.|Pročitajte prijevod (.txt)|Svi jezici|Datum tekstualnog prijevoda
hu|Magyar|Ez a nyelvi cím a cikkek gépi fordítását kínálja, kizárólag szöveges formában. A fordítást nem ellenőrizték függetlenül, és elavult lehet. A teljes weboldal csak csehül és angolul érhető el.|Fordítás olvasása (.txt)|Összes nyelv|A szövegfordítás dátuma
hy|Հայերեն|Այս լեզվային հասցեն առաջարկում է հոդվածների մեքենայական թարգմանությունը միայն տեքստի տեսքով։ Թարգմանությունն անկախ ստուգում չի անցել և կարող է հնացած լինել։ Ամբողջական կայքը հասանելի է միայն չեխերեն և անգլերեն։|Կարդալ թարգմանությունը (.txt)|Բոլոր լեզուները|Տեքստի թարգմանության ամսաթիվը
id|Bahasa Indonesia|Alamat bahasa ini menawarkan terjemahan mesin artikel dalam bentuk teks saja. Terjemahan belum ditinjau secara independen dan mungkin sudah tidak mutakhir. Situs lengkap hanya tersedia dalam bahasa Ceko dan Inggris.|Baca terjemahan (.txt)|Semua bahasa|Tanggal terjemahan teks
is|Íslenska|Þetta tungumálanetfang býður upp á vélþýðingu greinanna sem hreinan texta. Þýðingin hefur ekki verið yfirfarin óháð og gæti verið úrelt. Vefurinn í heild er aðeins fáanlegur á tékknesku og ensku.|Lesa þýðinguna (.txt)|Öll tungumál|Dagsetning textaþýðingar
it|Italiano|Questo indirizzo linguistico offre una traduzione automatica degli articoli in solo testo. La traduzione non è stata verificata in modo indipendente e potrebbe non essere aggiornata. Il sito completo è disponibile solo in ceco e inglese.|Leggi la traduzione (.txt)|Tutte le lingue|Data della traduzione del testo
ja|日本語|この言語別アドレスでは、記事の機械翻訳をテキストのみで提供しています。翻訳は独立した確認を受けておらず、最新の内容とは限りません。通常のウェブサイトはチェコ語と英語のみで利用できます。|翻訳を読む (.txt)|すべての言語|テキスト翻訳の日付
ka|ქართული|ეს ენობრივი მისამართი გთავაზობთ სტატიების მანქანურ თარგმანს მხოლოდ ტექსტის სახით. თარგმანი დამოუკიდებლად არ შემოწმებულა და შესაძლოა მოძველებული იყოს. სრული ვებსაიტი ხელმისაწვდომია მხოლოდ ჩეხურად და ინგლისურად.|თარგმანის წაკითხვა (.txt)|ყველა ენა|ტექსტის თარგმანის თარიღი
kk|Қазақша|Бұл тілдік мекенжай мақалалардың машиналық аудармасын тек мәтін түрінде ұсынады. Аударма тәуелсіз тексеруден өтпеген және ескірген болуы мүмкін. Толық сайт тек чех және ағылшын тілдерінде қолжетімді.|Аударманы оқу (.txt)|Барлық тілдер|Мәтін аудармасының күні
km|ខ្មែរ|អាសយដ្ឋានភាសានេះផ្តល់ការបកប្រែអត្ថបទដោយម៉ាស៊ីនជាទម្រង់អក្សរតែប៉ុណ្ណោះ។ ការបកប្រែមិនត្រូវបានពិនិត្យដោយឯករាជ្យទេ ហើយអាចហួសសម័យ។ គេហទំព័រពេញលេញមានតែជាភាសាឆែក និងអង់គ្លេសប៉ុណ្ណោះ។|អានការបកប្រែ (.txt)|ភាសាទាំងអស់|កាលបរិច្ឆេទការបកប្រែអត្ថបទ
kn|ಕನ್ನಡ|ಈ ಭಾಷೆಯ ವಿಳಾಸದಲ್ಲಿ ಲೇಖನಗಳ ಯಂತ್ರಾನುವಾದವು ಪಠ್ಯ ರೂಪದಲ್ಲಿ ಮಾತ್ರ ಲಭ್ಯವಿದೆ. ಅನುವಾದವನ್ನು ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿಲ್ಲ ಮತ್ತು ಅದು ಹಳೆಯದಾಗಿರಬಹುದು. ಸಂಪೂರ್ಣ ವೆಬ್‌ಸೈಟ್ ಚೆಕ್ ಮತ್ತು ಇಂಗ್ಲಿಷ್ ಭಾಷೆಗಳಲ್ಲಿ ಮಾತ್ರ ಲಭ್ಯವಿದೆ.|ಅನುವಾದ ಓದಿ (.txt)|ಎಲ್ಲ ಭಾಷೆಗಳು|ಪಠ್ಯ ಅನುವಾದದ ದಿನಾಂಕ
ko|한국어|이 언어별 주소에서는 기사의 기계 번역을 텍스트로만 제공합니다. 번역은 독립적인 검토를 거치지 않았으며 최신 내용이 아닐 수 있습니다. 전체 웹사이트는 체코어와 영어로만 제공됩니다.|번역 읽기 (.txt)|모든 언어|텍스트 번역 날짜
ku|Kurdî|Ev navnîşana zimanî wergera makîneyî ya gotaran tenê wekî nivîs pêşkêş dike. Werger bi serbixweyî nehatiye kontrolkirin û dibe ku kevn bibe. Malpera tevahî tenê bi çekî û îngilîzî berdest e.|Wergerê bixwîne (.txt)|Hemû ziman|Dîroka wergera nivîsê
ky|Кыргызча|Бул тилдик дарек макалалардын машиналык котормосун текст түрүндө гана сунуштайт. Котормо көз карандысыз текшерүүдөн өткөн эмес жана эскирип калган болушу мүмкүн. Толук сайт чех жана англис тилдеринде гана жеткиликтүү.|Котормону окуу (.txt)|Бардык тилдер|Тексттин котормосунун датасы
lo|ລາວ|ທີ່ຢູ່ພາສານີ້ສະເໜີການແປບົດຄວາມດ້ວຍເຄື່ອງໃນຮູບແບບຂໍ້ຄວາມເທົ່ານັ້ນ. ການແປຍັງບໍ່ໄດ້ຮັບການກວດສອບຢ່າງເປັນອິດສະຫຼະ ແລະອາດບໍ່ເປັນປັດຈຸບັນ. ເວັບໄຊເຕັມມີພຽງພາສາເຊັກ ແລະອັງກິດ.|ອ່ານຄຳແປ (.txt)|ທຸກພາສາ|ວັນທີຂອງການແປຂໍ້ຄວາມ
lt|Lietuvių|Šiuo kalbos adresu pateikiamas mašininis straipsnių vertimas tik tekstu. Vertimas nebuvo nepriklausomai patikrintas ir gali būti pasenęs. Visa svetainė prieinama tik čekų ir anglų kalbomis.|Skaityti vertimą (.txt)|Visos kalbos|Teksto vertimo data
lv|Latviešu|Šī valodas adrese piedāvā rakstu mašīntulkojumu tikai teksta veidā. Tulkojums nav neatkarīgi pārbaudīts un var būt novecojis. Pilnā vietne pieejama tikai čehu un angļu valodā.|Lasīt tulkojumu (.txt)|Visas valodas|Teksta tulkojuma datums
mi|Māori|Kei tēnei wāhitau reo he whakamāoritanga ā-mīhini o ngā tuhinga, he kuputuhi anake. Kāore anō kia arotakengia motuhaketia, ā, tērā pea kua tawhito. Kei te reo Tīeke me te reo Ingarihi anake te paetukutuku katoa.|Pānuihia te whakamāoritanga (.txt)|Ngā reo katoa|Te rā o te whakamāoritanga tuhinga
mk|Македонски|Оваа јазична адреса нуди машински превод на написите само како текст. Преводот не е независно проверен и може да е застарен. Целосната веб-страница е достапна само на чешки и англиски.|Прочитајте го преводот (.txt)|Сите јазици|Датум на преводот на текстот
ml|മലയാളം|ഈ ഭാഷാ വിലാസത്തിൽ ലേഖനങ്ങളുടെ യന്ത്രപരിഭാഷ പാഠരൂപത്തിൽ മാത്രം ലഭ്യമാണ്. പരിഭാഷ സ്വതന്ത്രമായി പരിശോധിച്ചിട്ടില്ല, അത് കാലഹരണപ്പെട്ടതാകാം. പൂർണ്ണ വെബ്സൈറ്റ് ചെക്ക്, ഇംഗ്ലീഷ് ഭാഷകളിൽ മാത്രമേ ലഭ്യമാകൂ.|പരിഭാഷ വായിക്കുക (.txt)|എല്ലാ ഭാഷകളും|പാഠപരിഭാഷയുടെ തീയതി
mn|Монгол|Энэ хэлний хаяг нийтлэлүүдийн машин орчуулгыг зөвхөн текстээр санал болгодог. Орчуулгыг хараат бус байдлаар хянаагүй бөгөөд хуучирсан байж болно. Бүрэн вэбсайт зөвхөн чех, англи хэлээр боломжтой.|Орчуулгыг унших (.txt)|Бүх хэл|Текстийн орчуулгын огноо
mr|मराठी|या भाषेच्या पत्त्यावर लेखांचे यंत्रानुवाद फक्त मजकूर स्वरूपात उपलब्ध आहेत. अनुवादाची स्वतंत्र तपासणी झालेली नाही आणि तो जुना असू शकतो. संपूर्ण वेबसाइट फक्त चेक आणि इंग्रजी भाषांत उपलब्ध आहे.|अनुवाद वाचा (.txt)|सर्व भाषा|मजकुराच्या अनुवादाची तारीख
ms|Bahasa Melayu|Alamat bahasa ini menawarkan terjemahan mesin bagi artikel dalam bentuk teks sahaja. Terjemahan belum disemak secara bebas dan mungkin tidak terkini. Laman web penuh hanya tersedia dalam bahasa Czech dan Inggeris.|Baca terjemahan (.txt)|Semua bahasa|Tarikh terjemahan teks
mt|Malti|Dan l-indirizz tal-lingwa joffri traduzzjoni awtomatika tal-artikli bħala test biss. It-traduzzjoni ma ġietx riveduta indipendentement u tista' tkun skaduta. Is-sit sħiħ huwa disponibbli biss biċ-Ċek u bl-Ingliż.|Aqra t-traduzzjoni (.txt)|Il-lingwi kollha|Data tat-traduzzjoni tat-test
my|မြန်မာ|ဤဘာသာစကားလိပ်စာတွင် ဆောင်းပါးများ၏ စက်ဘာသာပြန်ကို စာသားအဖြစ်သာ ဖတ်ရှုနိုင်သည်။ ဘာသာပြန်ကို သီးခြားစစ်ဆေးထားခြင်း မရှိသေးဘဲ ခေတ်မမီတော့ခြင်း ဖြစ်နိုင်သည်။ ဝဘ်ဆိုက်အပြည့်အစုံကို ချက်နှင့် အင်္ဂလိပ်ဘာသာဖြင့်သာ ရရှိနိုင်သည်။|ဘာသာပြန်ကို ဖတ်ရန် (.txt)|ဘာသာစကားအားလုံး|စာသားဘာသာပြန်ရက်စွဲ
ne|नेपाली|यस भाषाको ठेगानामा लेखहरूको यान्त्रिक अनुवाद केवल पाठका रूपमा उपलब्ध छ। अनुवादको स्वतन्त्र समीक्षा गरिएको छैन र यो पुरानो हुन सक्छ। पूर्ण वेबसाइट चेक र अङ्ग्रेजीमा मात्र उपलब्ध छ।|अनुवाद पढ्नुहोस् (.txt)|सबै भाषाहरू|पाठको अनुवादको मिति
nl|Nederlands|Dit taaladres biedt een machinevertaling van de artikelen als platte tekst. De vertaling is niet onafhankelijk gecontroleerd en kan verouderd zijn. De volledige website is alleen beschikbaar in het Tsjechisch en Engels.|Lees de vertaling (.txt)|Alle talen|Datum van de tekstvertaling
no|Norsk|Denne språkadressen tilbyr en maskinoversettelse av artiklene som ren tekst. Oversettelsen er ikke gjennomgått uavhengig og kan være utdatert. Hele nettstedet er bare tilgjengelig på tsjekkisk og engelsk.|Les oversettelsen (.txt)|Alle språk|Dato for tekstoversettelsen
om|Afaan Oromoo|Teessoon afaanii kun hiika maashinii barruulee akka barruu qofaatti dhiyeessa. Hiikni kun of danda'ee hin sakatta'amne; yeroon isaa darbe ta'uu danda'a. Marsariitiin guutuun afaan Cheekii fi Ingiliffaan qofa argama.|Hiika dubbisi (.txt)|Afaanota hunda|Guyyaa hiika barruu
or|ଓଡ଼ିଆ|ଏହି ଭାଷାର ଠିକଣାରେ ଲେଖାଗୁଡ଼ିକର ଯନ୍ତ୍ର ଅନୁବାଦ କେବଳ ପାଠ୍ୟ ରୂପରେ ମିଳେ। ଅନୁବାଦର ସ୍ୱାଧୀନ ସମୀକ୍ଷା ହୋଇନାହିଁ ଏବଂ ଏହା ପୁରୁଣା ହୋଇପାରେ। ସମ୍ପୂର୍ଣ୍ଣ ୱେବସାଇଟ୍ କେବଳ ଚେକ୍ ଏବଂ ଇଂରାଜୀରେ ଉପଲବ୍ଧ।|ଅନୁବାଦ ପଢ଼ନ୍ତୁ (.txt)|ସମସ୍ତ ଭାଷା|ପାଠ୍ୟ ଅନୁବାଦର ତାରିଖ
pa|ਪੰਜਾਬੀ|ਇਸ ਭਾਸ਼ਾ ਦੇ ਪਤੇ ਉੱਤੇ ਲੇਖਾਂ ਦਾ ਮਸ਼ੀਨੀ ਅਨੁਵਾਦ ਸਿਰਫ਼ ਪਾਠ ਵਜੋਂ ਉਪਲਬਧ ਹੈ। ਅਨੁਵਾਦ ਦੀ ਸੁਤੰਤਰ ਸਮੀਖਿਆ ਨਹੀਂ ਕੀਤੀ ਗਈ ਅਤੇ ਇਹ ਪੁਰਾਣਾ ਹੋ ਸਕਦਾ ਹੈ। ਪੂਰੀ ਵੈੱਬਸਾਈਟ ਸਿਰਫ਼ ਚੈੱਕ ਅਤੇ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਉਪਲਬਧ ਹੈ।|ਅਨੁਵਾਦ ਪੜ੍ਹੋ (.txt)|ਸਾਰੀਆਂ ਭਾਸ਼ਾਵਾਂ|ਪਾਠ ਦੇ ਅਨੁਵਾਦ ਦੀ ਮਿਤੀ
pl|Polski|Ten adres językowy oferuje maszynowe tłumaczenie artykułów wyłącznie w formie tekstowej. Tłumaczenie nie zostało niezależnie sprawdzone i może być nieaktualne. Pełna strona jest dostępna tylko po czesku i angielsku.|Czytaj tłumaczenie (.txt)|Wszystkie języki|Data tłumaczenia tekstu
ps|پښتو|دا ژبنی پته د مقالو ماشيني ژباړه یوازې د متن په بڼه وړاندې کوي. ژباړه په خپلواکه توګه نه ده کتل شوې او ښايي پخوانۍ وي. بشپړه وېبپاڼه یوازې په چکي او انګلیسي ژبو شته.|ژباړه ولولئ (.txt)|ټولې ژبې|د متن د ژباړې نېټه
pt-BR|Português (Brasil)|Este endereço de idioma oferece uma tradução automática dos artigos apenas em texto. A tradução não foi revisada de forma independente e pode estar desatualizada. O site completo está disponível apenas em tcheco e inglês.|Ler a tradução (.txt)|Todos os idiomas|Data da tradução do texto
pt-PT|Português (Portugal)|Este endereço de idioma oferece uma tradução automática dos artigos apenas em texto. A tradução não foi revista de forma independente e pode estar desatualizada. O site completo está disponível apenas em checo e inglês.|Ler a tradução (.txt)|Todos os idiomas|Data da tradução do texto
qu|Runasimi|Kay simip web tiyayninpi qillqakunap makina tikrasqan qillqallata tarinki. Tikrasqa mana sapanchasqa qhawasqachu, mawk'aña kanman. Llapan webqa checo simipi ingles simipipas sapallanmi kachkan.|Tikrasqata ñawinchay (.txt)|Llapan simikuna|Qillqa tikrasqap p'unchawnin
rm|Rumantsch|Questa adressa da lingua porscha ina translaziun automatica dals artitgels mo sco text. La translaziun n'è betg vegnida controllada independentamain e po esser antiquada. La pagina cumpletta è disponibla mo per tschec ed englais.|Leger la translaziun (.txt)|Tut las linguas|Data da la translaziun dal text
ro|Română|Această adresă de limbă oferă o traducere automată a articolelor doar ca text. Traducerea nu a fost verificată independent și poate fi învechită. Site-ul complet este disponibil doar în cehă și engleză.|Citește traducerea (.txt)|Toate limbile|Data traducerii textului
ru|Русский|Этот языковой адрес предлагает машинный перевод статей только в текстовом виде. Перевод не прошёл независимую проверку и может быть устаревшим. Полный сайт доступен только на чешском и английском.|Читать перевод (.txt)|Все языки|Дата текстового перевода
rw|Ikinyarwanda|Iyi aderesi y'ururimi itanga ubuhinduzi bw'ingingo bwakozwe n'imashini, mu nyandiko gusa. Ubuhinduzi ntibwasuzumwe mu buryo bwigenga kandi bushobora kuba butakijyanye n'igihe. Urubuga rwose ruboneka gusa mu Giceki no mu Cyongereza.|Soma ubuhinduzi (.txt)|Indimi zose|Itariki y'ubuhinduzi bw'inyandiko
sd|سنڌي|هي ٻوليءَ وارو پتو مضمونن جو مشيني ترجمو رڳو متن جي صورت ۾ پيش ڪري ٿو. ترجمي جي آزادانه جاچ نه ڪئي وئي آهي ۽ اهو پراڻو ٿي سگهي ٿو. مڪمل ويب سائيٽ رڳو چيڪ ۽ انگريزيءَ ۾ موجود آهي.|ترجمو پڙهو (.txt)|سڀ ٻوليون|متن جي ترجمي جي تاريخ
si|සිංහල|මෙම භාෂා ලිපිනය ලිපිවල යන්ත්‍ර පරිවර්තනය පෙළ ලෙස පමණක් සපයයි. පරිවර්තනය ස්වාධීනව සමාලෝචනය කර නොමැති අතර යල් පැන ගිය එකක් විය හැකිය. සම්පූර්ණ වෙබ් අඩවිය ඇත්තේ චෙක් සහ ඉංග්‍රීසි භාෂාවලින් පමණි.|පරිවර්තනය කියවන්න (.txt)|සියලු භාෂා|පෙළ පරිවර්තනයේ දිනය
sk|Slovenčina|Táto jazyková adresa ponúka strojový preklad článkov iba ako text. Preklad nebol nezávisle overený a môže byť neaktuálny. Plnohodnotný web je dostupný iba v češtine a angličtine.|Čítať preklad (.txt)|Všetky jazyky|Dátum textového prekladu
sl|Slovenščina|Ta jezikovni naslov ponuja strojni prevod člankov samo kot besedilo. Prevod ni bil neodvisno preverjen in je lahko zastarel. Celotna spletna stran je na voljo samo v češčini in angleščini.|Preberite prevod (.txt)|Vsi jeziki|Datum prevoda besedila
so|Soomaali|Cinwaankan luqadeed wuxuu bixiyaa tarjumaad mashiin oo maqaallada ah, qoraal keliya. Tarjumaadda si madax-bannaan looma hubin, waxaana laga yaabaa inay duugowday. Website-ka oo dhammaystiran waxaa lagu heli karaa Czech iyo Ingiriisi oo keliya.|Akhri tarjumaadda (.txt)|Dhammaan luqadaha|Taariikhda tarjumaadda qoraalka
sq|Shqip|Kjo adresë gjuhësore ofron një përkthim automatik të artikujve vetëm si tekst. Përkthimi nuk është kontrolluar në mënyrë të pavarur dhe mund të jetë i vjetruar. Faqja e plotë është e disponueshme vetëm në çekisht dhe anglisht.|Lexoni përkthimin (.txt)|Të gjitha gjuhët|Data e përkthimit të tekstit
sr|Srpski|Ova jezička adresa nudi mašinski prevod članaka samo u tekstualnom obliku. Prevod nije nezavisno proveren i može biti zastareo. Potpun sajt dostupan je samo na češkom i engleskom.|Pročitajte prevod (.txt)|Svi jezici|Datum tekstualnog prevoda
st|Sesotho|Aterese ena ea puo e fana ka phetolelo ea lingoloa ka mochini, e le mongolo feela. Phetolelo ha e so hlahlojoe ka boikemelo 'me e ka ba ea khale. Webosaete e feletseng e fumaneha feela ka Secheke le Senyesemane.|Bala phetolelo (.txt)|Lipuo tsohle|Letsatsi la phetolelo ea mongolo
sv|Svenska|Den här språkadressen erbjuder en maskinöversättning av artiklarna som ren text. Översättningen har inte granskats oberoende och kan vara inaktuell. Hela webbplatsen finns endast på tjeckiska och engelska.|Läs översättningen (.txt)|Alla språk|Datum för textöversättningen
sw|Kiswahili|Anwani hii ya lugha inatoa tafsiri ya mashine ya makala kama maandishi pekee. Tafsiri haijakaguliwa kwa kujitegemea na inaweza kuwa ya zamani. Tovuti kamili inapatikana kwa Kicheki na Kiingereza pekee.|Soma tafsiri (.txt)|Lugha zote|Tarehe ya tafsiri ya maandishi
ta|தமிழ்|இந்த மொழி முகவரி கட்டுரைகளின் இயந்திர மொழிபெயர்ப்பை உரையாக மட்டும் வழங்குகிறது. மொழிபெயர்ப்பு தனியாகச் சரிபார்க்கப்படவில்லை; அது காலாவதியானதாக இருக்கலாம். முழு இணையதளம் செக் மற்றும் ஆங்கிலத்தில் மட்டுமே கிடைக்கும்.|மொழிபெயர்ப்பைப் படிக்கவும் (.txt)|அனைத்து மொழிகளும்|உரை மொழிபெயர்ப்பின் தேதி
te|తెలుగు|ఈ భాషా చిరునామా వ్యాసాల యంత్ర అనువాదాన్ని పాఠ్యంగా మాత్రమే అందిస్తుంది. అనువాదాన్ని స్వతంత్రంగా సమీక్షించలేదు, అది పాతది కావచ్చు. పూర్తి వెబ్‌సైట్ చెక్ మరియు ఆంగ్ల భాషల్లో మాత్రమే అందుబాటులో ఉంది.|అనువాదం చదవండి (.txt)|అన్ని భాషలు|పాఠ్య అనువాదం తేదీ
tg|Тоҷикӣ|Ин нишонии забонӣ тарҷумаи мошинии мақолаҳоро танҳо дар шакли матн пешниҳод мекунад. Тарҷума мустақилона санҷида нашудааст ва метавонад кӯҳна бошад. Сомонаи пурра танҳо ба забонҳои чехӣ ва англисӣ дастрас аст.|Тарҷумаро хонед (.txt)|Ҳамаи забонҳо|Санаи тарҷумаи матн
th|ไทย|ที่อยู่สำหรับภาษานี้มีบทความที่แปลด้วยเครื่องในรูปแบบข้อความเท่านั้น คำแปลไม่ได้รับการตรวจสอบอย่างอิสระและอาจไม่เป็นปัจจุบัน เว็บไซต์ฉบับเต็มมีเฉพาะภาษาเช็กและภาษาอังกฤษ|อ่านคำแปล (.txt)|ทุกภาษา|วันที่แปลข้อความ
tk|Türkmençe|Bu dil salgysy makalalaryň maşyn terjimesini diňe tekst görnüşinde hödürleýär. Terjime garaşsyz barlanmady we könelen bolup biler. Doly web sahypasy diňe çeh we iňlis dillerinde elýeterlidir.|Terjimäni okaň (.txt)|Ähli diller|Tekst terjimesiniň senesi
tn|Setswana|Aterese eno ya puo e neela phetolelo ya ditlhogo ka motšhini, e le mokwalo fela. Phetolelo ga e a sekasekiwa ka boikemelo mme e ka tswa e le ya bogologolo. Webosaete e e feletseng e teng fela ka Se-Czech le Sekgoa.|Buisa phetolelo (.txt)|Dipuo tsotlhe|Letlha la phetolelo ya mokwalo
tr|Türkçe|Bu dil adresi, makalelerin makine çevirisini yalnızca metin olarak sunar. Çeviri bağımsız olarak incelenmemiştir ve güncel olmayabilir. Tam web sitesi yalnızca Çekçe ve İngilizce olarak mevcuttur.|Çeviriyi okuyun (.txt)|Tüm diller|Metin çevirisinin tarihi
uk|Українська|Ця мовна адреса пропонує машинний переклад статей лише в текстовому вигляді. Переклад не пройшов незалежну перевірку й може бути застарілим. Повний сайт доступний лише чеською та англійською.|Читати переклад (.txt)|Усі мови|Дата текстового перекладу
ur|اردو|یہ لسانی پتہ مضامین کا مشینی ترجمہ صرف متن کی صورت میں پیش کرتا ہے۔ ترجمے کا آزادانہ جائزہ نہیں لیا گیا اور یہ پرانا ہو سکتا ہے۔ مکمل ویب سائٹ صرف چیک اور انگریزی زبانوں میں دستیاب ہے۔|ترجمہ پڑھیں (.txt)|تمام زبانیں|متن کے ترجمے کی تاریخ
uz|O‘zbekcha|Bu til manzili maqolalarning mashina tarjimasini faqat matn shaklida taqdim etadi. Tarjima mustaqil tekshirilmagan va eskirgan bo‘lishi mumkin. To‘liq sayt faqat chex va ingliz tillarida mavjud.|Tarjimani o‘qing (.txt)|Barcha tillar|Matn tarjimasining sanasi
vi|Tiếng Việt|Địa chỉ ngôn ngữ này cung cấp bản dịch máy của các bài viết chỉ ở dạng văn bản. Bản dịch chưa được kiểm tra độc lập và có thể đã lỗi thời. Trang web đầy đủ chỉ có bằng tiếng Séc và tiếng Anh.|Đọc bản dịch (.txt)|Tất cả ngôn ngữ|Ngày dịch văn bản
wo|Wolof|Màkkaanu làkk bii dafay joxe tekki bu masin def ci jukki yi, ci mbind rekk. Tekki bi kenn saytu ko ci boppam te man naa nekk bu yàgg. Dalub web bi yépp am na ci làkku Cek ak Àngale rekk.|Jàng tekki bi (.txt)|Làkk yépp|Bésu tekki mbind mi
yo|Yorùbá|Àdírẹ́sì èdè yìí ní ìtumọ̀ ẹ̀rọ àwọn àpilẹ̀kọ gẹ́gẹ́ bí ọ̀rọ̀ kíkọ nìkan. A kò tíì ṣe àyẹ̀wò òmìnira sí ìtumọ̀ náà, ó sì lè ti di àtijọ́. Ojúlé wẹ́ẹ̀bù kíkún wà ní èdè Czech àti Gẹ̀ẹ́sì nìkan.|Ka ìtumọ̀ náà (.txt)|Gbogbo èdè|Ọjọ́ ìtumọ̀ ọ̀rọ̀ kíkọ
zh-Hans|简体中文|此语言地址提供文章的机器翻译，仅有纯文本。译文未经独立审核，内容可能已过时。完整网站仅提供捷克语和英语版本。|阅读译文 (.txt)|所有语言|文本翻译日期
zh-Hant|繁體中文|此語言網址提供文章的機器翻譯，僅有純文字。譯文未經獨立審核，內容可能已過時。完整網站僅提供捷克語和英語版本。|閱讀譯文 (.txt)|所有語言|文字翻譯日期
zu|IsiZulu|Leli kheli lolimi linikeza ukuhumusha kwezindatshana ngomshini njengombhalo kuphela. Ukuhumusha akukabuyekezwa ngokuzimela futhi kungase kube okudala. Iwebhusayithi ephelele itholakala kuphela ngesiCzech nangesiNgisi.|Funda ukuhumusha (.txt)|Zonke izilimi|Usuku lokuhunyushwa kombhalo
`.trim();

export type RosettaCopy = {
  name: string;
  notice: string;
  open: string;
  languages: string;
  translationDate: string;
};

export const rosettaCopy: Record<string, RosettaCopy> = Object.fromEntries(
  rows.split("\n").map((line) => {
    const fields = line.split("|");
    if (fields.length !== 6 || fields.some((field) => !field.trim())) {
      throw new Error(`Invalid Rosetta UI copy: ${line}`);
    }
    const [code, name, notice, open, languages, translationDate] = fields;
    return [code, { name, notice, open, languages, translationDate }];
  }),
);
