import fs from "node:fs";
import path from "node:path";

const distDir = path.resolve("dist");

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(full));
    else if (entry.isFile() && full.endsWith(".html")) files.push(full);
  }
  return files;
}

function rewriteHtml(html) {
  return html
    // CSS/JS/assets generated by Astro
    .replace(/(href|src)="\/_astro\//g, '$1="./_astro/')
    // public assets
    .replace(/(href|src)="\/images\//g, '$1="./images/')
    .replace(/(href|src)="\/files\//g, '$1="./files/')
    .replace(/(href|src)="\/demos\//g, '$1="./demos/')
    // homepage
    .replace(/href="\/"/g, 'href="./index.html"')
    // directory-style internal links -> flat html links
    .replace(/href="\/([^"/?#]+)\/"/g, 'href="./$1.html"');
}

const htmlFiles = walk(distDir);

for (const file of htmlFiles) {
  const original = fs.readFileSync(file, "utf8");
  const rewritten = rewriteHtml(original);
  fs.writeFileSync(file, rewritten, "utf8");
}

console.log(`Rewritten ${htmlFiles.length} HTML files for USB mode.`);